version: '3'
services:
  testrpc:
    image: dougvk/testrpc:latest
    command: bash -c "testrpc -h 0.0.0.0"
  truffle3:
    image: dougvk/truffle3:latest
    command: bash
    stdin_open: true
    tty: true
    volumes:
      - ../:/app
